### ISSUE TITLE
The script doesn't work with davinci resolve 19.1.1

### ISSUE THREAD

**Issue by Nachha** [TKtheDEV/davinci-resolve-installer-ubuntu#1]

**Comment by TKtheDEV** [comment]
I will take a look, sorry it has taken this long for me to answer!

**Comment by TKtheDEV** [comment]
sorry for your inconvenience @Nachha, its fixed now. please delete the old version of the script from your PC (likely to be in your home folder)

**Comment by TKtheDEV** [comment]
sorry for your inconvenience @Nachha, its fixed now. please delete the old version of the script from your PC (likely to be in your home folder)
